#!/bin/bash

set -o nounset
set -o errexit
set -o pipefail
IFS=$'\n\t'

NAME="project"
GROUP="com.example"
VERSION="1.0.0-SNAPSHOT"
PACKAGE="com.example"
MAIN_CLASS="ProjectPlugin"
AUTHOR="dandan2611"

# Name
echo -e "Project name ($NAME): \c"
read -r INPUT_NAME
NAME=${INPUT_NAME:-$NAME}

# Group
echo -e "Group ($GROUP): \c"
read -r INPUT_GROUP
GROUP=${INPUT_GROUP:-$GROUP}

# Version
echo -e "Version ($VERSION): \c"
read -r INPUT_VERSION
VERSION=${INPUT_VERSION:-$VERSION}

# Package
echo -e "Package ($PACKAGE): \c"
read -r INPUT_PACKAGE
PACKAGE=${INPUT_PACKAGE:-$PACKAGE}

# Main class
echo -e "Main class ($MAIN_CLASS): \c"
read -r INPUT_MAIN_CLASS
MAIN_CLASS=${INPUT_MAIN_CLASS:-$MAIN_CLASS}

# Author
echo -e "Author ($AUTHOR): \c"
read -r INPUT_AUTHOR
AUTHOR=${INPUT_AUTHOR:-$AUTHOR}

git clone https://github.com/PaperMC/paperweight-test-plugin.git work
cd work
rm -rf .git

sed -i "s/rootProject.name = .*/rootProject.name = \"$NAME\"/" settings.gradle.kts
sed -i "s/group = .*/group = \"$GROUP\"/" build.gradle.kts
sed -i "s/version = .*/version = \"$VERSION\"/" build.gradle.kts
sed -i "s/description = .*/description = \"A Minecraft plugin\"/" build.gradle.kts

PACKAGE_WITH_SLASHES=$(echo "$PACKAGE" | sed 's/\./\//g')
mkdir -p "src/main/java/$PACKAGE_WITH_SLASHES"
mv src/main/java/io/papermc/paperweight/testplugin/* "src/main/java/$PACKAGE_WITH_SLASHES"
rm -rf src/main/java/io
sed -i "s/io.papermc.paperweight.testplugin/$PACKAGE/" "src/main/java/$PACKAGE_WITH_SLASHES/TestPlugin.java"
sed -i "s/io.papermc.paperweight.testplugin/$PACKAGE/" "src/main/java/$PACKAGE_WITH_SLASHES/PluginBrigadierCommand.java"

sed -i "s/main: .*/main: $PACKAGE.$MAIN_CLASS/" src/main/resources/plugin.yml
sed -i "s/- Author/- dandan2611/" src/main/resources/plugin.yml
mv "src/main/java/$PACKAGE_WITH_SLASHES/TestPlugin.java" "src/main/java/$PACKAGE_WITH_SLASHES/$MAIN_CLASS.java"
